# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1b5ae89946b74b8e7e1e72dcedf0caba68308ad11f155f9e34b65199588d04f10f9670d60d5832728bb6c0d012c6e41af51a18a24d85c6b0c858df9f1ed349

test:
  secret_key_base: f7b6967d4b1a59f85c2c1a506b7be70924ec21964c88d14690966d5cc8ebbb3996dd70ed28b20f32af8af7a43a029fb030deb44108dd640f0e462585a66e174f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
